[package]
name = "sirin-cli"
version.workspace = true
edition.workspace = true

# The compiler driver is invoked as `sirin` (like `rustc` or `clang`).
[[bin]]
name = "sirin"
path = "src/main.rs"

[dependencies]
sirin-parser       = { workspace = true }
sirin-diagnostics  = { workspace = true }
sirin-lexer        = { workspace = true }
sirin-typechecker  = { workspace = true }
sirin-codegen-c    = { workspace = true }
clap               = { workspace = true }
logos              = { workspace = true }
chumsky            = { workspace = true }
