[workspace]
members = ["sirin-cli","sirin-diagnostics","sirin-lexer", "sirin-parser","sirin-runtime", "sirin-typechecker"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
ariadne = "0.6.0"
clap = "4.5.27"
logos = "0.16.1"
chumsky = { version = "0.13.0", features = ["pratt"] }

sirin-lexer = { path = "sirin-lexer" }
sirin-parser = { path = "sirin-parser" }
sirin-diagnostics = { path = "sirin-diagnostics" }
sirin-typechecker = { path = "sirin-typechecker" }