//! The C runtime linked into every Sirin program. The sources live in
//! `sirin-runtime/` and are embedded here, so an installed compiler needs no
//! extra files. A build writes them to a directory, together with a generated
//! `sirin_config.h`, and compiles the `.c` files next to the program.

use std::path::{Path, PathBuf};

/// Which optional parts of the runtime a program needs.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Features {
    pub io: bool,
    pub async_: bool,
    pub net: bool,
}

impl Features {
    fn includes(self, part: Part) -> bool {
        match part {
            Part::Core => true,
            // Sockets wait by yielding to the scheduler, so net pulls in async.
            Part::Async => self.async_ || self.net,
            Part::Net => self.net,
        }
    }
}

/// What a program needs from the runtime: the optional parts, and the
/// `SIRIN_USE_*` switches for the collection element types it uses.
#[derive(Clone, Debug, Default)]
pub struct RuntimeConfig {
    pub features: Features,
    pub defines: Vec<String>,
}

impl RuntimeConfig {
    /// Contents of `sirin_config.h` for this program.
    pub fn header(&self) -> String {
        let mut defines = self.defines.clone();
        if self.features.includes(Part::Async) {
            defines.push("SIRIN_USE_ASYNC".to_string());
        }
        if self.features.net {
            defines.push("SIRIN_USE_NET".to_string());
        }
        defines.sort();
        defines.dedup();

        let mut out = String::from(
            "/* Generated by the Sirin compiler for this program. */\n\
             #ifndef SIRIN_CONFIG_H\n#define SIRIN_CONFIG_H\n",
        );
        for d in &defines {
            out.push_str(&format!("#define {}\n", d));
        }
        out.push_str("#endif\n");
        out
    }

    /// Write the runtime into `dir` and return the `.c` files to compile.
    pub fn write_to(&self, dir: &Path) -> Result<Vec<PathBuf>, String> {
        let mut sources = Vec::new();
        for file in FILES.iter().filter(|f| self.features.includes(f.part)) {
            let path = dir.join(file.path);
            write_file(&path, file.contents)?;
            if file.path.ends_with(".c") {
                sources.push(path);
            }
        }
        write_file(&dir.join("sirin_config.h"), &self.header())?;
        Ok(sources)
    }
}

fn write_file(path: &Path, contents: &str) -> Result<(), String> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("cannot create {}: {}", parent.display(), e))?;
    }
    std::fs::write(path, contents).map_err(|e| format!("cannot write {}: {}", path.display(), e))
}

#[derive(Clone, Copy, PartialEq, Eq)]
enum Part {
    Core,
    Async,
    Net,
}

struct RuntimeFile {
    path: &'static str,
    contents: &'static str,
    part: Part,
}

macro_rules! runtime_file {
    ($part:ident, $path:literal) => {
        RuntimeFile {
            path: $path,
            contents: include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../sirin-runtime/", $path)),
            part: Part::$part,
        }
    };
}

/// Every runtime file, by the part it belongs to. `sirin_config.h` is not
/// here: it is generated per program (see `RuntimeConfig::header`).
const FILES: &[RuntimeFile] = &[
    runtime_file!(Core, "sirin_runtime.h"),
    runtime_file!(Core, "core/mem.h"),
    runtime_file!(Core, "core/mem.c"),
    runtime_file!(Core, "core/str.h"),
    runtime_file!(Core, "core/str.c"),
    runtime_file!(Core, "core/json.h"),
    runtime_file!(Core, "core/json.c"),
    runtime_file!(Core, "core/io.h"),
    runtime_file!(Core, "core/io.c"),
    runtime_file!(Core, "collections/vec.h"),
    runtime_file!(Core, "collections/vec.c"),
    runtime_file!(Core, "collections/array.h"),
    runtime_file!(Core, "collections/array.c"),
    runtime_file!(Core, "collections/set.h"),
    runtime_file!(Core, "collections/set.c"),
    runtime_file!(Core, "collections/map.h"),
    runtime_file!(Core, "collections/map.c"),
    // core/io.c includes async/sched.h when SIRIN_USE_ASYNC is set, so the
    // header ships with every build.
    runtime_file!(Core, "async/sched.h"),
    runtime_file!(Async, "sirin_async.h"),
    runtime_file!(Async, "async/context.h"),
    runtime_file!(Async, "async/sched.c"),
    runtime_file!(Async, "async/context_win32.c"),
    runtime_file!(Async, "async/context_posix.c"),
    runtime_file!(Async, "async/channel.h"),
    runtime_file!(Async, "async/channel.c"),
    runtime_file!(Net, "sirin_net.h"),
    runtime_file!(Net, "net/sys.h"),
    runtime_file!(Net, "net/sys.c"),
    runtime_file!(Net, "net/tcp.h"),
    runtime_file!(Net, "net/tcp.c"),
    runtime_file!(Net, "net/udp.h"),
    runtime_file!(Net, "net/udp.c"),
];

#[cfg(test)]
mod tests {
    use super::*;

    fn written(features: Features) -> (tempdir::Dir, Vec<String>) {
        let dir = tempdir::Dir::new();
        let config = RuntimeConfig { features, defines: vec!["SIRIN_USE_VEC_INT".into()] };
        let sources = config.write_to(dir.path()).unwrap();
        let names = sources
            .iter()
            .map(|p| p.strip_prefix(dir.path()).unwrap().to_string_lossy().replace('\\', "/"))
            .collect();
        (dir, names)
    }

    #[test]
    fn core_only_program_skips_async_and_net() {
        let (dir, sources) = written(Features::default());
        assert!(sources.contains(&"core/str.c".to_string()));
        assert!(!sources.iter().any(|s| s.starts_with("async/") || s.starts_with("net/")));
        let config = std::fs::read_to_string(dir.path().join("sirin_config.h")).unwrap();
        assert!(config.contains("#define SIRIN_USE_VEC_INT"));
        assert!(!config.contains("SIRIN_USE_ASYNC"));
    }

    #[test]
    fn net_pulls_in_async() {
        let (dir, sources) = written(Features { net: true, ..Default::default() });
        assert!(sources.contains(&"net/tcp.c".to_string()));
        assert!(sources.contains(&"async/sched.c".to_string()));
        let config = std::fs::read_to_string(dir.path().join("sirin_config.h")).unwrap();
        assert!(config.contains("#define SIRIN_USE_ASYNC"));
    }

    #[test]
    fn every_listed_file_exists_once() {
        let mut paths: Vec<&str> = FILES.iter().map(|f| f.path).collect();
        paths.sort();
        let before = paths.len();
        paths.dedup();
        assert_eq!(before, paths.len(), "a runtime file is listed twice");
    }

    #[test]
    fn every_runtime_source_is_listed() {
        fn walk(dir: &Path, root: &Path, out: &mut Vec<String>) {
            for entry in std::fs::read_dir(dir).unwrap().flatten() {
                let path = entry.path();
                if path.is_dir() {
                    walk(&path, root, out);
                } else if matches!(path.extension().and_then(|e| e.to_str()), Some("c" | "h")) {
                    out.push(path.strip_prefix(root).unwrap().to_string_lossy().replace('\\', "/"));
                }
            }
        }
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../sirin-runtime");
        let mut on_disk = Vec::new();
        walk(&root, &root, &mut on_disk);
        for path in on_disk.iter().filter(|p| *p != "sirin_config.h") {
            assert!(
                FILES.iter().any(|f| f.path == path),
                "sirin-runtime/{path} is not listed in FILES, so builds would not ship it"
            );
        }
    }

    /// Minimal temp dir for tests, removed on drop.
    mod tempdir {
        use std::path::{Path, PathBuf};
        use std::sync::atomic::{AtomicUsize, Ordering};

        pub struct Dir(PathBuf);

        impl Dir {
            pub fn new() -> Self {
                static NEXT: AtomicUsize = AtomicUsize::new(0);
                let path = std::env::temp_dir().join(format!(
                    "sirin_runtime_test_{}_{}",
                    std::process::id(),
                    NEXT.fetch_add(1, Ordering::Relaxed)
                ));
                std::fs::create_dir_all(&path).unwrap();
                Dir(path)
            }

            pub fn path(&self) -> &Path {
                &self.0
            }
        }

        impl Drop for Dir {
            fn drop(&mut self) {
                let _ = std::fs::remove_dir_all(&self.0);
            }
        }
    }
}
